version: '3.7'
services:
  postgres:
    image: postgres:12
    restart: on-failure
    environment:
      POSTGRES_DB: shopping
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5433:5432'
    volumes:
      - db-data:/var/lib/postgresql/data:cached

  backend:
    image: sl_base
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "alembic upgrade head && python app/initial_data.py && python app/main.py"
    ports:
      - '8888:8888'
    volumes:
      - ./backend:/src/:cached
    environment:
      PYTHONPATH: .
      DATABASE_URL: 'postgresql://postgres:postgres@postgres:5432/shopping'
      LOG_LEVEL: 'debug'
      FIRST_ADMIN: 'admin'
      FIRST_ADMIN_PASSWORD: 'admin_pass'
    depends_on:
      - postgres

volumes:
  db-data: