version: '3.7'
services:
  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: shopping
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5433:5432'
    volumes:
      - db-data:/var/lib/postgresql/data:cached

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: python app/main.py
    ports:
      - '8888:8888'
    volumes:
      - ./backend:/app/:cached
    environment:
      PYTHONPATH: .
      DATABASE_URL: 'postgresql://postgres:postgres@postgres:5432/shopping'
    depends_on:
      - 'postgres'

volumes:
  db-data: