version: '3.7'
services:
  test_postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: shopping_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - test-db-data:/var/lib/postgresql/data:cached

  test_backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: bash -c "alembic -c app/alembic.ini upgrade head && pytest -vvvv"
    volumes:
      - type: bind
        source: ./backend
        target: /src
    environment:
      PYTHONPATH: .
      DATABASE_URL: 'postgresql://postgres:postgres@test_postgres:5432/shopping_test'
    depends_on:
      - 'test_postgres'

volumes:
  test-db-data: