version: '3'

env:
  PYTHON: 3.10.0
  POETRY: 1.2.0a2

tasks:
  setup:
    cmds:
      - task: setup:python
      - task: setup:poetry
      - task: setup:virtualenv

  setup:python:
    cmds:
      - cmd: asdf plugin add python
        ignore_error: true
      - asdf plugin update python
      - asdf install python $PYTHON
      - asdf local python $PYTHON
    preconditions:
      - sh: "asdf help"
        msg: "asdf is required to run this task"

  setup:poetry:
    cmds:
      - cmd: asdf plugin add poetry
        ignore_error: true
      - asdf plugin update poetry
      - asdf install poetry $POETRY
      - asdf local poetry $POETRY
    preconditions:
      - sh: "asdf help"
        msg: "asdf is required to run this task"

  setup:virtualenv:
    cmds:
      - poetry env use $(which python)
    status:
      - poetry env info -p
    preconditions:
      - sh: "poetry -V"
        msg: "poetry is required to run this task"

  install:
    cmds:
      - poetry install
    sources:
      - pyproject.toml
      - poetry.lock
    preconditions:
      - sh: "poetry -V"
        msg: "poetry is required to run this task"

  build:
    cmds:
      - docker-compose build
    preconditions:
      - sh: "docker-compose version"
        msg: "docker-compose is required to run this task"

  build:scratch:
    cmds:
      - docker-compose build --no-cache
    preconditions:
      - sh: "docker-compose version"
        msg: "docker-compose is required to run this task"

  test:build:
    cmds:
      - docker-compose -f test-docker-compose.yml build
    preconditions:
      - sh: "docker-compose version"
        msg: "docker-compose is required to run this task"

  test:abort:
    cmds:
      - docker-compose -f test-docker-compose.yml down
    preconditions:
      - sh: "docker-compose version"
        msg: "docker-compose is required to run this task"

  test:
    cmds:
      - docker-compose -f test-docker-compose.yml up -d test_postgres
      - docker-compose -f test-docker-compose.yml run --rm test_backend
      - docker-compose -f test-docker-compose.yml down
    preconditions:
      - sh: "docker-compose version"
        msg: "docker-compose is required to run this task"

  format:
    cmds:
      - poetry run isort app tests
      - poetry run black app tests
    preconditions:
      - sh: "poetry -V"
        msg: "poetry is required to run this task"

  run:db:
    cmds:
      - docker-compose up -d postgres

  run:app:
    cmds:
      - python app/main.py
  run:in-docker:
    cmds:
      - docker-compose up -d
    preconditions:
      - sh: "docker-compose version"
        msg: "docker-compose is required to run this task"

  stop:docker:
    cmds:
      - docker-compose down
    preconditions:
      - sh: "docker-compose version"
        msg: "docker-compose is required to run this task"