version: '3.7'
services:
  test_postgres:
    image: postgres:14.0-alpine
    restart: on-failure
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - test-db-data:/var/lib/postgresql/data:cached

  test_backend:
    build:
      context: .
      dockerfile: test.dockerfile
    command: bash -c "poetry run alembic upgrade head && poetry run pytest -vvv"
    environment:
      PYTHONPATH: .
      DATABASE_URL: 'postgresql://postgres:postgres@test_postgres:5432/shopping'
    depends_on:
      - test_postgres

volumes:
  test-db-data: